FROM openjdk:8u121-jre-alpine
ADD target/telemontelas-1.0-SNAPSHOT.jar telemontelas-1.0-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /telemontelas-1.0-SNAPSHOT.jar"]